/**
 * This is your Notion-as-Code script. It describes Notion resources —
 * teamspaces, pages, databases, and entries — as code.
 *
 * Build and apply it with the Notion CLI:
 *
 *   ntn notion-as-code apply .
 *
 * Re-running apply updates the same records instead of creating new ones,
 * because the mapping from resourceIds to real Notion IDs is saved per state
 * name (default "default"; pick another with --name). List saved states with
 * `ntn notion-as-code list`.
 *
 * Try changing names, page content, properties, or add more entries, then
 * re-apply.
 *
 * Note: The resourceIds below are stable and will let future runs update the same resources.
 */

import { welcomeContent } from "./content"
import sampleRows from "./data/sample-projects.json" with { type: "json" }
import { notion } from "./lib/notion"

const spaceParent = {
  type: "resourceId",
  resourceId: "my-cool-space",
} as const

// The spaceParent resourceId above anchors this script to the workspace you
// are logged into; the CLI seeds that mapping automatically on first apply.
// The new resources below are created inside this space.
// addTeamspace(...) parents this new General teamspace to the space above.
const generalTeamspace = notion.teamspace({
  resourceId: "general-teamspace",
  parent: spaceParent,
  name: "Notion as Code Home",
  accessLevel: "open",
  icon: { type: "notion_icon", description: "home", color: "lightgray" },
  description: "A starting point created by Notion as Code.",
})

// This creates a top-level page in the General teamspace with an icon, title, and content.
generalTeamspace.addPage({
  resourceId: "hello-world-page",
  properties: { title: notion.text("Hello world!") },
  icon: { type: "notion_icon", description: "sparkles", color: "yellow" },
  // The content of the page is written in Notion-flavored markdown. It is
  // imported from src/content.ts to show that scripts can span multiple files.
  content: welcomeContent,
})

// This creates a database in the General teamspace with some sample projects.
const sampleDatabase = generalTeamspace.addDatabase({
  resourceId: "sample-projects-db",
  name: "Projects",
  icon: { type: "notion_icon", description: "database", color: "purple" },
  description: "A small seeded database generated by Notion as Code.",
  dataSources: [
    {
      resourceId: "sample-projects-ds",
      name: "Sample Projects",
      // This array defines the properties that database pages can set.
      // The resourceIds below are stable and will let future runs update the same columns.
      properties: [
        { resourceId: "project-name-prop", name: "Name", type: "title" },
        {
          resourceId: "project-status-prop",
          name: "Status",
          type: "status",
          options: {
            todo: [{ name: "Not Started", color: "gray", default: true }],
            inProgress: [{ name: "In Progress", color: "blue" }],
            complete: [{ name: "Done", color: "green" }],
          },
        },
        {
          resourceId: "project-priority-prop",
          name: "Priority",
          type: "select",
          options: [
            { name: "High", color: "red" },
            { name: "Medium", color: "yellow" },
            { name: "Low", color: "green" },
          ],
        },
        {
          resourceId: "project-target-date-prop",
          name: "Target",
          type: "date",
        },
        { resourceId: "project-notes-prop", name: "Notes", type: "text" },
      ],
    },
  ],
})

// Get the data source handle so we can add sample entries to the database.
// "sample-projects-ds" matches the resourceId of the data source we created above.
const sampleProjects = sampleDatabase.getDataSource("sample-projects-ds")

// These database pages are sample entries, seeded from a JSON file to show
// that scripts can be data-driven: the build runs under Node, so importing
// JSON (or reading files with node:fs) works out of the box.
// You can try adding more rows in src/data/sample-projects.json -- just make
// sure to give each one a unique resourceId.
for (const row of sampleRows) {
  sampleProjects.addPage({
    resourceId: row.resourceId,
    properties: {
      Name: notion.text(row.name),
      Status: notion.status(row.status),
      Priority: notion.select(row.priority),
      Target: notion.date(row.target),
      Notes: notion.text(row.notes),
    },
  })
}
